version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: auth
    volumes: 
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - auth

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
   
      
  nginxapp:
    build: ./test_apps/app3
    container_name: nginxapp
    depends_on:
      - phpmyadmin
    ports:
      - 8000:8000
    

  nodeapp:
    build: ./test_apps/app1
    container_name: nodeapp
    depends_on:
      - nginxapp
    ports:
      - 8081:8000
    
  pyapp:
    build: ./test_apps/app2
    container_name: pyapp
    
    ports:
      - 8082:8000
    networks:
      - auth

  authapp:
    build: ./auth_app
    container_name: authapp
    env_file:
      - .env
    ports:
      - 80:3000
    networks:
      - auth

networks:
  auth:




# docker-compose -f docker-compose.override.yml up -d
# docker-compose up --build