version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: auth
    volumes: 
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - auth

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - 80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    networks:
      - auth
    
  pyapp:
    build: ./test_apps/py_app
    container_name: pyapp
    depends_on:
      - db
    expose:
      - 8002
    networks:
      - auth

  nodeapp:
    build: ./test_apps/node_app
    container_name: nodeapp
    depends_on:
      - db
    ports:
      - 8001
    networks:
      - auth

  authapp:
    build: ./auth_app
    container_name: authapp
    env_file:
      - .env
    expose:
      - 3000
    networks:
      - auth

  nginxapp:
    build: ./test_apps/nginx
    container_name: nginxapp
    restart: always
    depends_on:
      - authapp
      - pyapp
      - nodeapp
      - db
    ports:
      - 80:80
    networks:
      - auth

networks:
  auth:




# docker-compose -f docker-compose_prod.yml up -d
# docker-compose -f docker-compose_prod.yml up --build
# docker-compose -f docker-compose_prod.yml down