version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: auth
    volumes: 
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - auth

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - auth
  app1:
    build: ./test_apps/app1
    container_name: app1
    ports:
      - 8081:8081
    networks:
      - auth
  app2:
    build: ./test_apps/app2
    container_name: app2
    ports:
      - 8082:8082
    networks:
      - auth
  app3:
    build: ./test_apps/app3
    container_name: app3
    ports:
      - 8083:8000
    networks:
      - auth

  
networks:
  auth:




# docker-compose -f docker-compose.override.yml up -d
# docker-compose up --build