version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: auth
    volumes: 
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - auth

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - auth
    
  pyapp:
    build: ./test_apps/py_app
    container_name: pyapp
    depends_on:
      - db
    ports:
      - 8002:8002
    networks:
      - auth

  nodeapp:
    build: ./test_apps/node_app
    container_name: nodeapp
    depends_on:
      - db
    ports:
      - 8001:8001
    networks:
      - auth


  nginxapp:
    build: ./test_apps/nginx
    container_name: nginxapp
    restart: always
    depends_on:
      - pyapp
      - nodeapp
      - db
    ports:
      - 8000:8000
    networks:
      - auth

networks:
  auth:

