version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: auth
    volumes: 
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - auth

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

    
  pyapp:
    build: ./test_apps/app2
    container_name: pyapp
    depends_on:
      - db
    expose:
      - 8002
    networks:
      - auth

  nodeapp:
    build: ./test_apps/app1
    container_name: nodeapp
    depends_on:
      - db
    ports:
      - 8001
    networks:
      - auth

  authapp:
    build: ./auth_app
    container_name: authapp
    env_file:
      - .env
    ports:
      - 8000:3000
    networks:
      - auth

  nginxapp:
    build: ./test_apps/app3
    container_name: nginxapp
    depends_on:
      - authapp
      - pyapp
      - nodeapp
      - db
    ports:
      - 80:80

networks:
  auth:




# docker-compose -f docker-compose.override.yml up -d
# docker-compose up --build